# Setup
title:            "Elizabeth Tran"
logo:             gallery/profilepiccircle.png
tagline:          ''
description:      Trying to go from a potato to a French fry ~ 
url:              https://elizabellatran.github.io/
baseurl:          ''

author:
  name:           'Elizabeth'

# Navigation
nav:
  - title: "Home"
    url: "/https://elizabellatran.github.io/" 


markdown: kramdown
kramdown: 
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages
highlighter:      rouge
# Permalinks
# permalink:        pretty

# Custom vars
# version:          2.1.0
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
