
markdown: kramdown
kramdown: 
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "Elizabeth Tran"
tagline:          ''
description:      ''
url:              https://elizabellatran.github.io/
baseurl:          ''

author:
  name:           'Yang Xiaozhou'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/elizabellatran/elizabellatran.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages